import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./breeze.css";
import GustWave from "../components/shared/gustWave"; // Assuming you place it here

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sarva Holidays",
  description: "Generated by create next app",
};

export default function RootLayout({children} ) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-[#ecfdf5] to-white min-h-screen`}
      >
        <GustWave />
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
