import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./breeze.css";
import PublicChrome from "../components/shared/public-chrome";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sarva Holidays",
  description: "Generated by create next app",
  icons: {
    icon: '/leaf-favicon.svg',
    shortcut: '/leaf-favicon.svg',
    apple: '/leaf-favicon.svg',
  },
};

export default function RootLayout({children} ) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-[#ecfdf5] to-white min-h-screen`}
      >
        <PublicChrome />
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
